pipeline{
    agent any
    stages{
        stage("Deploy Back-end Node.js"){
            steps{
                sh "sudo cp /home/jrbn/work/pucminas/sica-microservices-node/comunicacao/.env sica-microservices-node/comunicacao"
               // sh "cd sica-microservices-node && docker-compose up -d --build"
            }
        }
    }   
}
