pipeline{
    agent any
    stages{
        stage("Build Back-end Node.js"){
            steps{
                sh "sudo chmod 777 /home/jrbn/work/pucminas/sica-microservices-node/comunicacao/.env && sudo -S cp /home/jrbn/work/pucminas/sica-microservices-node/comunicacao/.env /var/lib/jenkins/workspace/Back-End-Node/sica-microservices-node/comunicacao" 
            }
        }
        stage("Deploy Back-end Node.js"){
            steps{               
                sh "cd sica-microservices-node && docker-compose up -d --build"
            }
        }
    }   
}
