server:
  port: 8082
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

spring:
  application:
    name: monitoramento

  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: guest
    password: guest

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
  # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.lob:
          non_contextual_creation: true

  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://192.168.56.101:5433/sica_barragem
    driver-class-name: org.postgresql.Driver
    username: root
    password: 12345 

url:
  api:
    auth:
      user: http://localhost:8083/user/

mq:
  alert:
    exchange: alert.monitoramento.exchange
    queue: 
      barragem: alert.barragem.queue 
      morador: alert.morador.queue
    routingkey: 
      barragem: alert.barragem.routingkey
      morador: alert.morador.routingkey
      

jwt:
  config:
    type: signed
