pipeline {
  stages {
        stage('Test') {
            steps {
                sh 'export JAVA_HOME="/home/flavio/applications/jdk-11"'
                sh 'java -version'
            }
        }
    }
}
