spring:
  application:
    name: discovery
server:
  port: 8081

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.56.101:${server.port}/eureka/