version: '3.1'

services:
      
  discovery:
    container_name: discovery
    image: discovery
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8081:8081"    
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 360M

  auth:
    container_name: auth
    image: auth
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8083:8083"
    links:
      - discovery
    depends_on:
      - discovery
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 350M

  ativo:
    container_name: ativo
    image: ativo
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8084:8084"
    links:
      - discovery
    depends_on:
      - discovery
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 370M

  monitoramento:
    container_name: monitoramento
    image: monitoramento
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8082:8082"
    links:
      - discovery
    depends_on:
      - discovery
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 370M
 
  workflow:
    container_name: workflow
    image: workflow
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8086:8086"
    links:
      - discovery
    depends_on:
      - discovery
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 370M

  hystrix-dashboard:
    container_name: hystrix-dashboard
    image: hystrix-dashboard
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "7979:7979"
    links:
      - discovery
    depends_on:
      - discovery
    deploy:
      resources:
        limits:
          memory: 350M
        reservations:
          memory: 300M
            
  gateway:
    container_name: gateway
    image: gateway
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "80:8080"
    depends_on:
      - discovery
      - auth
      - barragem
      - ativo
      - workflow
      - monitoramento
    deploy:
      resources:
        limits:
          memory: 380M
        reservations:
          memory: 350M
