pipeline{
    agent any
    stages{
        stage("Build Backend Java"){
            steps{
                sh "sudo su && cd sica-microservices-java && mvn clean install -Dmaven.test.skip=true"
            }
        }
    }   
}
