version: '3.1'

services:

  sicaadminapp:
    container_name: sicaadminapp
    image: sicaadminapp
    build:
      context: ./sica-admin-app
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
        - "3000:80"
    labels:
        NAME: "sicaadminapp"
    volumes:
      - .:/app

  sicamoradorapp:
    container_name: sicamoradorapp
    image: sicamoradorapp
    build:
      context: ./sica-morador-app
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
        - "3001:80"
    labels:
        NAME: "sicamoradorapp"
    volumes:
      - .:/app
   