pipeline{
    agent any
    stages{
        stage("Deploy Frontend"){
            steps{
                sh "cd sica-frontend && docker-compose build"
                sh "cd sica-frontend && docker-compose up -d"
            }
        }
    }   
}
