pipeline{
    agent any
    stages{
        stage("Build Front-end React"){
            steps{
                echo ">>> Build!!! gerando os arquivos .env com as variáveis ambiente"
                sh "sudo cp ~/applications/pucminas/sica-frontend/sica-admin-app/.env /var/lib/jenkins/jobs/sica-front/workspace/sica-frontend/sica-admin-app"
                sh "sudo chmod 777 /var/lib/jenkins/jobs/sica-front/workspace/sica-frontend/sica-admin-app/.env"
              }
        }

        stage("Deploy Front-end React"){
            steps{
                echo ">>> Deploy!!!"
                sh "cd sica-frontend && docker-compose up -d --build"
            }
        }
    }
}
