spring:
  application:
    name: gateway
server:
  port: 8080
  servlet:
    context-path: /api

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.56.101:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

zuul:
  sensitive-headers: Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

jwt:
  config:
    login-url: /auth/login
    type: signed

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000