spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /${segment}
        - id: barragem
          uri: lb://monitoramento
          predicates:
            - Path=/api/barragem/**
          filters:
            - RewritePath=/api/barragem/(?<segment>.*), /${segment}
        - id: monitoramento
          uri: lb://monitoramento
          predicates:
            - Path=/api/monitoramento/**
          filters:
            - RewritePath=/api/monitoramento/(?<segment>.*), /${segment}
        - id: ativo
          uri: lb://ativo
          predicates:
            - Path=/api/ativo/**
          filters:
            - RewritePath=/api/ativo/(?<segment>.*), /${segment}

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  config:
    login-url: /auth/login
    type: signed
